<form class="update-timeline-form" method="post">
    <div class="form-container">
        <div class="form-header">
            @update_password_label@
        </div>

        <div class="form-input-wrapper">
            <label class="float-left span35">
                @current_password_label@:
            </label>

            <div class="input float-left span55">
                <input type="password" name="current_password">
            </div>

            <div class="float-clear"></div>
        </div>

        <div class="form-input-wrapper">
            <label class="float-left span35">
                @new_password_label@:
            </label>

            <div class="input float-left span55">
                <input type="text" name="new_password">
            </div>

            <div class="float-clear"></div>
        </div>

        <div class="form-input-wrapper">
            <button class="active">
                @save_changes_button@
            </button>
        </div>
    </div>
</form>

<script>
$(function () {
    $('form.update-timeline-form').ajaxForm({
        url: SK_source()+'?t=user&a=settings',
        
        success: function (responseText) {
            
            if (responseText.status == 200) {
                
                $('.form-header').after('<div class="success-message hidden">@changes_saved@</div>');
                $('.success-message').fadeIn('fast',function () {
                        $(this).fadeOut(1500, function() {
                            $(this).remove();
                        });
                    });
                
                $('form.update-timeline-form').resetForm();
            }
            else {
                $('.form-header').after('<div class="success-message hidden">@passwords_not_match@</div>');
                $('.success-message').fadeIn('fast',function () {
                        $(this).fadeOut(1500, function() {
                            $(this).remove();
                        });
                    });
            }
        }
    });
});
</script>