<script>
$(function(){
    $('.timeline-370').css('min-height', ($('.timeline-sidebar').height() + 150) + 'px');
    $('.cover-resize-wrapper').height($('.cover-resize-wrapper').width()*0.3);
    
    $('form.cover-form').ajaxForm({
        url: SK_source() + '?t=cover&a=new',
        
        beforeSend: function() {
            $('.cover-progress')
                .html('0% @uploaded@...')
                .css('line-height', $('.cover-resize-wrapper').height() + 'px')
                .fadeIn('fast')
                .removeClass('hidden');
        },
        
        uploadProgress: function(event, position, total, percentComplete) {
            var percentVal = percentComplete + '%';
            
            $('.cover-progress').html(percentVal + ' @uploaded@...');
            
            if (percentComplete == 100) {
                
                setTimeout(function () {
                    $('.cover-progress').html('@processing@..');
                    
                    setTimeout(function () {
                        $('.cover-progress').html('@please_wait@...');
                    },2000);
                },500);
            }
        },
        
        success: function(responseText) {
            
            if (responseText.status == 200) {
                $('.cover-wrapper img')
                    .attr('src', responseText.cover_url + '?' + new Date().getTime())
                    .load(function() {
                        $('.cover-progress').fadeOut('fast', function(){
                            $(this).addClass('hidden').html('');
                        });
                        $('.cover-resize-wrapper img').attr('src', responseText.actual_cover_url + '?' + new Date().getTime()).css('top',0);
                    });
            }
            else {
                $('.cover-progress').fadeOut('fast', function(){
                    $(this).addClass('hidden').html('');
                });
                $('.cover-resize-wrapper img').css('top', 0);
            }
        }
    });
    
    $('form.cover-position-form').ajaxForm({
        url: SK_source()+'?t=cover&a=reposition',
        
        beforeSend: function() {
            $('.cover-progress').html('@repositioning@...').fadeIn('fast').removeClass('hidden');
        },
        
        success: function(responseText){
            
            if (responseText.status == 200) {
                $('.cover-wrapper img')
                    .attr('src', responseText.url + '?' + new Date().getTime())
                    .load(function () {
                        $('.cover-progress').fadeOut('fast').addClass('hidden').html('');
                        $('.cover-wrapper').show();
                        $('.cover-resize-wrapper')
                            .hide()
                            .find('img').css('top', 0);
                        $('.cover-resize-buttons').hide();
                        $('.default-buttons').show();
                        $('input.cover-position').val(0);
                        $('.cover-resize-wrapper img').draggable('destroy').css('cursor','default');
                    });
            }
        }
    });
    
    $(window).resize(function () {
        cover_width = $('.cover-resize-wrapper').width();
        $('.cover-resize-wrapper').height(cover_width * 0.3);
        $('.cover-resize-wrapper img').css('top', 0);
        $('.cover-progress').css('line-height', $('.cover-resize-wrapper').height() + 'px');
        $('.screen-width').val(cover_width);
    });
});

function SK_repositionCover() {
    cover_wrapper = $('.cover-wrapper');
    cover_resize_wrapper = $('.cover-resize-wrapper');
    cover_resize_buttons = $('.cover-resize-buttons');
    default_buttons = $('.default-buttons');
    screen_width = $('.screen-width');
    cover_position_input = $('input.cover-position');
    
    cover_wrapper.hide();
    cover_resize_wrapper.show();
    cover_resize_buttons.show();
    default_buttons.hide();
    screen_width.val(cover_resize_wrapper.width());
    cover_position_input.val(0);
    
    cover_resize_wrapper.find('img')
    .css('cursor','s-resize')
    .draggable({
        scroll: false,
        axis: "y",
        cursor: "s-resize",
        drag: function(event, ui) {
            y1 = $('.timeline-header-wrapper').height();
            y2 = cover_resize_wrapper.find('img').height();
            
            if (ui.position.top >= 0) {
                ui.position.top = 0;
            }
            else
            if (ui.position.top <= (y1-y2)) {
                ui.position.top = y1-y2;
            }
        },
        
        stop: function(event, ui) {
            cover_position_input.val(ui.position.top);
        }
    });
}

function SK_saveReposition() {
    
    if ($('input.cover-position').length == 1) {
        posY = $('input.cover-position').val();
        $('form.cover-position-form').submit();
    }
}

function SK_cancelReposition() {
    $('.cover-wrapper').show();
    $('.cover-resize-wrapper').hide();
    $('.cover-resize-buttons').hide();
    $('.default-buttons').show();
    $('input.cover-position').val(0);
    $('.cover-resize-wrapper img').draggable('destroy').css('cursor','default');
}
</script>