<div class="list-wrapper">
    <div class="list-header">
        @group_requests_label@
    </div>
    
    {{GROUP_REQUEST_USERLISTS}}
</div>
<script>
function SK_acceptGroupMember(group_id, member_id) {
    $('.group-member-' + member_id).find('.accept-btn').val('Accepting..');
    
    $.post(SK_source() + '?t=group&a=accept_member', {group_id: group_id, member_id: member_id}, function (data) {
        
        if (data.status == 200) {
            $('.group-member-' + member_id).slideUp(function () {
                $(this).remove();
            });
        }
    });
}

function SK_declineGroupMember(group_id, member_id) {
    $('.group-member-' + member_id).find('.decline-btn').val('Declining..');
    
    $.post(SK_source() + '?t=group&a=remove_member', {group_id: group_id, member_id: member_id}, function (data) {
        
        if (data.status == 200) {
            $('.group-member-' + member_id).slideUp(function () {
                $(this).remove();
            });
        }
    });
}
</script>