<div class="list-column group-member-{{GROUP_REQUEST_USER_ID}}">
    <table border="0" width="100%" cellspacing="0" cellpadding="0">
    <tr>
        <td width="42px" align="left" valign="middle">
            <a href="{{GROUP_REQUEST_USER_URL}}" data-href="?tab1=timeline&id={{GROUP_REQUEST_USERNAME}}">
                <img width="36px" height="36px" class="radius100" src="{{GROUP_REQUEST_USER_THUMBNAIL_URL}}" alt="{{GROUP_REQUEST_USER_NAME}}">
            </a>
        </td>
        
        <td align="left" valign="middle">
            <a class="bold-500" href="{{GROUP_REQUEST_USER_URL}}" data-href="?tab1=timeline&id={{GROUP_REQUEST_USERNAME}}">
                {{GROUP_REQUEST_USER_NAME}}
            </a>
        </td>
        
        {{GROUP_REQUESTS_BTN}}
    </tr>
    </table>
</div>