<div class="list-column group-admin-{{LIST_ADMIN_USER_ID}}">
    <table border="0" width="100%" cellspacing="0" cellpadding="0">
    <tr>
        <td width="42px" align="left" valign="middle">
            <a href="{{LIST_ADMIN_USER_URL}}" data-href="?tab1=timeline&id={{LIST_ADMIN_USERNAME}}">
                <img width="36px" height="36px" class="radius100" src="{{LIST_ADMIN_USER_THUMBNAIL_URL}}" alt="{{LIST_ADMIN_USER_NAME}}">
            </a>
        </td>
        
        <td align="left" valign="middle">
            <a class="bold-500" href="{{LIST_ADMIN_USER_URL}}" data-href="?tab1=timeline&id={{LIST_ADMIN_USERNAME}}">
                {{LIST_ADMIN_USER_NAME}}
            </a>
        </td>
        
        {{LIST_ADMINS_BTN}}
    </tr>
    </table>
</div>