<div class="float-right span35">
    {{TIMELINE_BUTTONS_HTML}}

    {{TIMELINE_INFO_HTML}}


    <div>


    	<div class="dd-55">
    			{{ADD_GROUP_MEMBERS_HTML}}
		</div>
      

    	<div class="dd-55">
    			{{GROUP_MEMBERS_HTML}}
		</div>


    	<div class="dd-55">
    			{{GROUP_ADMINS_HTML}}
		</div>


    	<div class="dd-55">
    			{{GROUP_POSTS_HTML}}
		</div>


		<div class="dd-55">
    			{{GROUP_REQUESTS_HTML}}	
		</div>


    </div>
</div>