<div class="list-column suggestion-{{LIST_SUGGESTION_ID}}">
    <table border="0" width="100%" cellspacing="0" cellpadding="0">
    <tr>
        <td width="42px" align="left" valign="middle">
            <a href="{{LIST_SUGGESTION_URL}}" data-href="?tab1=timeline&id={{LIST_SUGGESTION_USERNAME}}">
                <img width="36px" height="36px" class="radius100" src="{{LIST_SUGGESTION_THUMBNAIL_URL}}" alt="{{LIST_SUGGESTION_NAME}}">
            </a>
        </td>
        
        <td width="45%" align="left" valign="middle">
            <a class="bold-500" href="{{LIST_SUGGESTION_URL}}" data-href="?tab1=timeline&id={{LIST_SUGGESTION_USERNAME}}">
                {{LIST_SUGGESTION_NAME}}
            </a>

            <div class="info">
               
            </div>
        </td>

        <td class="column-btn" align="right" valign="middle">
            {{LIST_SUGGESTION_BUTTON}}
        </td>
    </tr>
    </table>
</div>