<div class="chat-container">
    <div class="online-wrapper">
        <div class="online-header" onclick="javascript:$('.online-content-toggler').toggle();">
            <i class="icon-circle chat-icon"></i> 
            
            @chat_label@
            
            (<span class="online-count">{{NUM_ONLINES}}</span>)
            
            <span class="update-alert hidden">
                @chat_new_update_alert@
            </span>
        </div>

        <div class="online-content-toggler">
            <div class="online-list">
                {{LIST_ONLINES}}
            </div>

            <div class="online-search">
                <input type="text" placeholder="@chat_search_label@" onkeyup="SK_getOnlineList(this.value);">
            </div>
        </div>
    </div>
</div>
<form class="chat-photo-upload"></form>
<script>
initial_creq_time = 5000;

// Update online list
function SK_updateOnlineList()
{
    chat_container = $('.chat-container');
    
    if (chat_container.length == 1)
    {
        if ($('.online-search input').val().length == 0)
        {
            $.get(SK_source(), {t: 'search', a: 'online'}, function (data)
            {
                if (data.status == 200)
                {
                    $('.online-list').html(data.html);
                }
                
                $('.online-count').text($('.online-list .column').length);
            });
        }
    }
}

// Search online list
function SK_getOnlineList(query) {
    
    if (query.length == 0) {
        SK_updateOnlineList();
    }
    else {
        chat_container = $('.chat-container');
        
        if (chat_container.length == 1) {
            
            $.get (SK_source(), {t: 'search', a: 'online', q: query}, function (data) {
                
                if (data.html.length == 0) {
                    $('.online-list').html('<div class="no-wrapper" align="center">@no_search_result@</div>');
                }
                else {
                    $('.online-list').html(data.html);
                }
                
                $('.online-count').text($('.online-list .column').length);
            });
        }
    }
}

function addEmoToChat(code) {
    inputTag = $('.chat-textarea textarea');
    inputVal = inputTag.val();
    $('.chat-emoticons-wrapper').hide();
    
    if (typeof(inputTag.attr('placeholder')) != "undefined") {
        inputPlaceholder = inputTag.attr('placeholder');
        
        if (inputPlaceholder == inputVal) {
            inputTag.val('');
            inputVal = inputTag.val();
        }
        
    }
    
    if (inputVal.length == 0) {
        inputTag.val(code + ' ');
    } else {
        inputTag.val(inputVal + ' ' + code);
    }
    
    inputTag.keyup().focus();
}

function loadNewChatMessages()
{
    if (typeof($(document.body).attr('data-chat-recipient')) == "string")
    {
        recipient_id = $(document.body).attr('data-chat-recipient');
        
        $.get(SK_source(), {t: 'chat', a: 'load_new_messages', recipient_id: recipient_id}, function (data) {
            
            if (data.status == 200) {
                initial_creq_time = 5000;
                
                // Get new chat messages
                $('.chat-messages')
                    .append(data.html)
                    .scrollTop($('.chat-messages').prop('scrollHeight'));
                
                document.getElementById('notification-sound').play();
                
                if (!$('.chat-textarea').is(':focus')) {
                    document.title = '(@chat_new_update_alert@) ' + document_title;
                }
                
                SK_intervalUpdates();
            } else {
                initial_creq_time = initial_creq_time + 2000;
            }
            
            // Check if recipient is online
            cfrnd_online = false;
            
            if (typeof(data.online) == "boolean") {
                
                if (data.online == true) {
                    cfrnd_online = true;
                }
            }
            
            if (cfrnd_online == true) {
                $('.chat-header').find('.online-icon').addClass('active');
                SK_updateOnlineList();
            } else {
                $('.chat-header').find('.online-icon').removeClass('active');
            }
        });
    }
    
    setTimeout(function() {
        loadNewChatMessages();
    }, initial_creq_time);
}

// Send chat message
function SK_sendChatMessage(text,recipient_id,e) {
    document.title = document_title;
    textarea_wrapper = $('.chat-textarea');
    chat_messages_wrapper = $('.chat-messages');
    
    if (e.keyCode == 13 && e.shiftKey == 0) {
        e.preventDefault();
        textarea_wrapper.find('textarea').val('');
        chat_messages_wrapper.append('<div class="chat-text align-right temp-text" align="right"><div class="text-wrapper float-right">' + text + '<div class="marker-out"><div class="marker-in"></div></div></div><div class="float-clear"></div></div>');
        
        $.post(SK_source() + '?t=chat&a=send_message', {text: text, recipient_id: recipient_id}, function (data) {
            chat_messages_wrapper
                .append(data.html)
                .scrollTop(chat_messages_wrapper.prop('scrollHeight'))
                .find('.temp-text')
                    .remove();
        });
    }
}

// Focus on chat
function SK_focusChat() {
    document.title = document_title;
}

// Close chat
function SK_closeChat() {
    $('.chat-wrapper').remove();
    $(document.body).removeAttr('data-chat-recipient');
    $.get(SK_source(), {t: 'chat', a: 'close'});
}

setInterval('SK_updateOnlineList();', 40000);
setTimeout(function() {
    loadNewChatMessages();
}, initial_creq_time);
</script>