<div class="chat-text align-left" title="{{MESSAGE_TIME}}">
    <a class="float-left" href="{{MESSAGE_USER_URL}}">
        <img class="user-avatar" src="{{MESSAGE_USER_AVATAR_URL}}" width="32px" height="32px" valign="top" alt="{{MESSAGE_USER_NAME}}">
    </a>
    <div class="text-wrapper float-left">
        <div class="marker-out"><div class="marker-in"></div></div>

        {{MESSAGE_TEXT}}

        {{MESSAGE_MEDIA}}
    </div>
    <div class="float-clear"></div>
</div>