<div class="setting-buttons">
    {{STORY_REMOVE_BUTTON}}

    {{STORY_REPORT_BUTTON}}
</div>

<div class="options-wrapper">

<!-- 



    <div class="story-react-container">
        <span class="story-like-activity">
            {{STORY_LIKE_ACTIVITY}}
        </span>
    </div>
    
    
    
    &nbsp;&nbsp;&nbsp;
     <span class="story-share-activity">
            {{STORY_SHARE_ACTIVITY}}
     </span>


     

 -->

    &nbsp;&nbsp;&nbsp;
    <span style="float: right;">
        {{STORY_NOTIFICATION_BUTTON}}
    </span>
    
    
</div>