<div class="story-react-wrapper">
	<span data-title="Like" onclick="set_reaction('like', {{STORY_ID}});">
		<img src="{{CONFIG_SITE_URL}}/assets/imgs/reaction_like.png" alt="Like">
	</span>

	<span data-title="Clap" onclick="set_reaction('love', {{STORY_ID}});">
		<img src="{{CONFIG_SITE_URL}}/assets/imgs/reaction_clap.png" alt="Clap" data-title="Clap">
	</span>

	<span data-title="Curious" onclick="set_reaction('haha', {{STORY_ID}});">
		<img src="{{CONFIG_SITE_URL}}/assets/imgs/reaction_curious.png" alt="Curious" data-title="Curious">
	</span>

	<span data-title="Idea" onclick="set_reaction('wow', {{STORY_ID}});">
		<img src="{{CONFIG_SITE_URL}}/assets/imgs/reaction_idea.png" alt="Idea" data-title="Idea">
	</span>

	<span data-title="Sad" onclick="set_reaction('sad', {{STORY_ID}});">
		<img src="{{CONFIG_SITE_URL}}/assets/imgs/reaction_sad.png" alt="Sad" data-title="Sad">
	</span>
	
	<span data-title="Inappropriate" onclick="set_reaction('angry', {{STORY_ID}});">
		<img src="{{CONFIG_SITE_URL}}/assets/imgs/reaction_bad.png" alt="Inappropriate" data-title="Inappropriate">
	</span>
</div>