<div class="list-column">
    <table border="0" width="100%" cellspacing="0" cellpadding="0">
    <tr>
        <td width="42px" align="left" valign="middle">
            <a href="{{LIST_SEARCH_URL}}" data-href="?tab1=timeline&id={{LIST_SEARCH_USERNAME}}">
                <img width="36px" height="36px" class="radius3" src="{{LIST_SEARCH_THUMBNAIL_URL}}" alt="{{LIST_SEARCH_NAME}}">
            </a>
        </td>
        <td align="left" valign="middle">
            <a class="bold-500" href="{{LIST_SEARCH_URL}}" data-href="?tab1=timeline&id={{LIST_SEARCH_USERNAME}}">
                {{LIST_SEARCH_NAME}}
            </a>
        </td>
        <td class="column-btn" align="right" valign="middle">
            {{LIST_SEARCH_BUTTON}}
        </td>
    </tr>
    </table>
</div>