<div class="window-list-wrapper">
    <table border="0" width="100%" cellspacing="0" cellpadding="0">
    <tr>
        <td width="40px" align="left" valign="middle">
            <a href="{{LIST_LIKER_URL}}">
                <img class="avatar" src="{{LIST_LIKER_THUMBNAIL_URL}}" width="32px" alt="{{LIST_LIKER_NAME}}">
            </a>
        </td>
        <td align="left" valign="middle">
            <a class="name" href="{{LIST_LIKER_URL}}">
                {{LIST_LIKER_NAME}}
            </a>
        </td>
        <td class="window-btn" align="right" valign="middle">
            {{LIST_LIKER_BUTTON}}
        </td>
    </tr>
    </table>
</div>