<div style="font-size: 16px;">
    <div style="padding:15px;font-weight:bold;">
        <a href="{{FOLLOWERS_URL}}">You have a new follower!</a>
    </div>
    
    <p>
       <div><strong>Hi, {{MAIL_RECIPIENT_NAME}}</strong></div>
       
       <div><a href="{{MAIL_GENERATOR_URL}}">{{MAIL_GENERATOR_NAME}}</a> is following you at {{CONFIG_SITE_NAME}}. <a href="{{FOLLOWERS_URL}}">Click here</a> to see a list of all your followers.</div>
    </p>
</div>