<div style="font-size: 16px;">
    <div style="padding:15px;font-weight:bold;">
        <a href="{{CONVERSATION_URL}}">You have a new message!</a>
    </div>
    
    <p>
       <div><strong>Hi, {{MAIL_RECIPIENT_NAME}}</strong></div>

       <br>

       <div><a href="{{MAIL_GENERATOR_URL}}">{{MAIL_GENERATOR_NAME}}</a> has sent you a <a href="{{CONVERSATION_URL}}">message</a>.</div>
    </p>
</div>