<div style="font-size: 16px;">
    <div style="padding:15px;font-weight:bold;">
        <a href="{{FRIEND_REQUESTS_URL}}">New Friend Request</a>
    </div>
    
    <p>
       <div><strong>Hi, {{MAIL_RECIPIENT_NAME}}</strong></div>
       
       <div>You have received a new friend request from <a href="{{MAIL_GENERATOR_URL}}">{{MAIL_GENERATOR_NAME}}</a>. <a href="{{FRIEND_REQUESTS_URL}}">Click here</a> to respond to this friend request.</div>
    </p>
</div>