<div style="font-size: 16px;">
    <div style="padding:15px;font-weight:bold;">
        <a href="{{GROUP_URL}}">You have a new group member!</a>
    </div>
    
    <p>
       <div><strong>Hi, {{MAIL_RECIPIENT_NAME}}</strong></div>

       <br>

       <div><a href="{{MAIL_GENERATOR_URL}}">{{MAIL_GENERATOR_NAME}}</a> has joined your group <a href="{{GROUP_URL}}">{{GROUP_NAME}}</a>.</div>
    </p>
</div>