<div style="font-size: 16px;">
    <div style="padding:15px;font-weight:bold;">
        <a href="{{STORY_URL}}">You have a new share on your post</a>
    </div>
    
    <p>
       <div><strong>Hi, {{MAIL_RECIPIENT_NAME}}</strong></div>

       <br>

       <div><a href="{{MAIL_GENERATOR_URL}}">{{MAIL_GENERATOR_NAME}}</a> has shared one of <a href="{{STORY_URL}}">your posts</a>.</div>
    </p>
</div>