<div style="font-size: 16px;">
    <div style="padding:15px;font-weight:bold;">
        <a href="{{STORY_URL}}">You have a post on your timeline</a>
    </div>
    
    <p>
       <div><strong>Hi, {{MAIL_RECIPIENT_NAME}}</strong></div>

       <br>

       <div><a href="{{MAIL_GENERATOR_URL}}">{{MAIL_GENERATOR_NAME}}</a> has posted on <a href="{{STORY_URL}}">your timeline</a>.</div>
    </p>
</div>