<div class="announcement-container">
    <div class="announcement-header">
        <div class="float-left">
            @announcements@
        </div>

        <div class="float-right">
            <a href="javascript:void(0);" onclick="javascript:closeAnnouncements();">
                @close@
            </a>
        </div>

        <div class="float-clear"></div>
    </div>

    {{LIST_ANNOUNCEMENTS}}
</div>