<!DOCTYPE html>
<html>
<head>
	<meta name="googlebot" content="noindex">
	<meta name="robots" content="nofollow,noindex,noarchive,noimageindex">
    {{HEADER_TAGS}}
    <style>
    .mejs-container .mejs-controls
    {
    	background: #29a8b7 !important;
    }
    .mejs-controls .mejs-time-rail .mejs-time-total
    {
    	background: linear-gradient(rgba(30,30,30,.2),rgba(60,60,60,.4)) !important;
    }
    .mejs-controls .mejs-time-rail .mejs-time-loaded
    {
    	background: linear-gradient(rgba(36, 95, 110, 0.8),rgba(31, 100, 120, 0.8)) !important;
    }
    .mejs-controls .mejs-horizontal-volume-slider .mejs-horizontal-volume-total
    {
    	background: linear-gradient(rgba(30,30,30,.2),rgba(60,60,60,.4)) !important;
    }
    </style>
</head>

<body data-rewrite="{{BODY_REWRITE_ATTR}}">
    {{HEADER}}
    
    <div class="page-wrapper">
        {{PAGE_CONTENT}}
    </div>
    
    {{FOOTER}}
</body>
</html>