<td class="statistic" align="center" valign="middle">
    <a href="{{FOLLOWING_TAB_URL}}" data-href="?tab1=timeline&tab2=following&id={{TIMELINE_USERNAME}}">
        {{FOLLOWING_NUM}} @following_label@
    </a>
</td>

<td class="statistic" align="center" valign="middle">
    <a href="{{FOLLOWERS_TAB_URL}}" data-href="?tab1=timeline&tab2=followers&id={{TIMELINE_USERNAME}}">
        {{FOLLOWERS_NUM}} @followers_label@
    </a>
</td>