<div class="sidebar-div">
    <table border="0" width="100%" cellspacing="0" cellpadding="0">
        <tr>
            <td width="25px" align="left" valign="top">
                <i class="icon-calendar"></i>
            </td>
            
            <td align="left" valign="top">
                {{TIMELINE_BIRTH_DATE}} {{TIMELINE_BIRTH_MONTH_NAME}}, {{TIMELINE_BIRTH_YEAR}}
            </td>
        </tr>
    </table>
</div>