<div class="list-column follow-request-{{LIST_REQUEST_ID}}">
    <table border="0" width="100%" cellspacing="0" cellpadding="0">
    <tr>
        <td width="42px" align="left" valign="middle">
            <a href="{{LIST_REQUEST_URL}}" data-href="?tab1=timeline&id={{LIST_REQUEST_USERNAME}}">
                <img width="36px" height="36px" class="radius100" src="{{LIST_REQUEST_THUMBNAIL_URL}}" alt="{{LIST_REQUEST_NAME}}">
            </a>
        </td>
        
        <td align="left" valign="middle">
            <a class="bold-500" href="{{LIST_REQUEST_URL}}" data-href="?tab1=timeline&id={{LIST_REQUEST_USERNAME}}">
                {{LIST_REQUEST_NAME}}
            </a>
        </td>
        
        {{LIST_REQUEST_BUTTONS}}
    </tr>
    </table>
</div>