<div class="list-column">
    <table border="0" width="100%" cellspacing="0" cellpadding="0">
    <tr>
        <td width="42px" align="left" valign="middle">
            <a href="{{LIST_PAGE_URL}}" data-href="?tab1=timeline&id={{LIST_PAGE_USERNAME}}">
                <img width="36px" height="36px" class="radius100" src="{{LIST_PAGE_THUMBNAIL_URL}}" alt="{{LIST_PAGE_NAME}}">
            </a>
        </td>
        <td align="left" valign="middle">
            <a class="bold-500" href="{{LIST_PAGE_URL}}" data-href="?tab1=timeline&id={{LIST_PAGE_USERNAME}}">
                {{LIST_PAGE_NAME}}
            </a>
        </td>
        <td class="column-btn" align="right" valign="middle">
            {{LIST_LIKE_BUTTON}}
        </td>
    </tr>
    </table>
</div>