<div class="footer-wrapper">
    <div class="footer-content" align="center">
     
        
  
        
        <div class="footer-line">
            <span style="color: #b1b1b1">W&nbsp;&nbsp;e</span>
            &nbsp;&nbsp;&nbsp;&nbsp;
            <span style="color: #b1b1b1">a&nbsp;&nbsp;r&nbsp;&nbsp;e</span>
            &nbsp;&nbsp;&nbsp;&nbsp;
            <span style="color: #b1b1b1">M&nbsp;&nbsp;I&nbsp;&nbsp;U&nbsp;&nbsp;A&nbsp;&nbsp;N&nbsp;&nbsp;S</span>
        </div>
    </div>
</div>