<a href="{{ABOUT_PAGE_URL}}" data-href="?tab1=terms&tab2=notice">
    notice
</a> - 

<a href="{{CREATE_PAGE_URL}}" data-href="?tab1=create_page">
    @page_create_label@
</a> - 

<a href="{{CREATE_GROUP_URL}}" data-href="?tab1=create_group">
    @group_create_label@
</a> - 

<a href="{{CONTACT_PAGE_URL}}" data-href="?tab1=terms&tab2=contact">
    @terms_contact_label@
</a> - 

<a href="{{PRIVACY_PAGE_URL}}" data-href="?tab1=terms&tab2=privacy">
    @terms_privacy_label@
</a> - 

<a href="{{TOS_PAGE_URL}}" data-href="?tab1=terms&tab2=tos">
    @terms_tos_label@
</a> - 

<a href="{{DISCLAIMER_PAGE_URL}}" data-href="?tab1=terms&tab2=disclaimer">
    @terms_disclaimer_label@
</a> - 

<a href="{{DEVELOPERS_PAGE_URL}}" data-href="?tab1=terms&tab2=developers">
    @terms_developers_label@
</a> - 

<a href="{{ADMIN_URL}}">
    @admin_link_label@
</a>