<div class="list-column follower-{{LIST_USER_ID}}">
    <table border="0" width="100%" cellspacing="0" cellpadding="0">
    <tr>
        <td width="42px" align="left" valign="middle">
            <a href="{{LIST_USER_URL}}">
                <img width="36px" height="36px" class="radius100" src="{{LIST_USER_THUMBNAIL_URL}}" alt="{{LIST_USER_NAME}}">
            </a>
        </td>
        <td width="45%" align="left" valign="middle">
            <a class="bold-500" href="{{LIST_USER_URL}}">
                {{LIST_USER_NAME}}
            </a>

            <div class="info">
                {{LIST_USER_INFO}}
            </div>
        </td>
        <td class="column-btn" align="right" valign="middle">
            {{LIST_USER_BUTTON}}
        </td>
    </tr>
    </table>
</div>