<?php
$themeData['header_metatags'] = \miuan\UI::view('global/header/metatags');
$themeData['header_title'] = \miuan\UI::view('global/header/title');
$themeData['header_favicon'] = \miuan\UI::view('global/header/favicon');
$themeData['header_stylesheets'] = \miuan\UI::view('global/header/stylesheets');
$themeData['header_stylesheets'] .= (__GET__('tab1') == "welcome") ? '<link rel="stylesheet" href="' . $config['theme_url'] . '/css/welcome.css">' : '';
$themeData['header_scripts'] = \miuan\UI::view('global/header/scripts');
$themeData['header_scripts'] .= ($config['smooth_links'] == 1) ? '<script>function reqSource(){return \'' . $config['ajax_path'] . '\';}function SK_source(){return \'' . $config['ajax_path'] . '\';}function SK_pageSource(){return \'' . $config['page_path'] . '\';}function reqSource(){return \'' . $config['ajax_path'] . '\';}function pageSource(){return \'' . $config['page_path'] . '\';}</script>' : '<script>function reqSource(){return \'request.php\';}function SK_source(){return \'request.php\';}function SK_pageSource(){return \'page.php\';}function reqSource(){return \'request.php\';}function pageSource(){return \'page.php\';}</script>';
$themeData['header_scripts'] .= ($isLogged) ? '<script src="' . $config['theme_url'] . '/javascript/script.js"></script>' : '<script src="' . $config['theme_url'] . '/javascript/welcome.js"></script>';
$themeData['header_scripts'] .= ($config['chat'] == 1) ? ($chat_recipient = SK_getChat()) ? '<script>$(function(){SK_getChat(' . $chat_recipient['id'] . ',\'' . $chat_recipient['name'] . '\');});</script>' : "" : "";
$themeData['page_load_js'] = ($isLogged) ? '<script>function SK_loadPage(r){$.get(SK_pageSource()+r,{},function(t){stopPageLoadingBar(),$(".page-wrapper").html(t),"function"==typeof window.history.pushState&&(historyurl=r,1==$("body").attr("data-rewrite")&&(historyurl=historyurl.replace(/\?tab1=timeline&tab2=([^\/]+)&tab3=([^\/]+)&recipient_id=([^\/]+)&id=([^\/]+)$/i,"' . $config['site_url'] . '/@$4/$1/$2/$3"),historyurl=historyurl.replace(/\?tab1=timeline&tab2=([^\/]+)&tab3=([^\/]+)&id=([^\/]+)$/i,"' . $config['site_url'] . '/@$3/$1/$2"),historyurl=historyurl.replace(/\?tab1=timeline&tab2=([^\/]+)&id=([^\/]+)$/i,"' . $config['site_url'] . '/@$2/$1"),historyurl=historyurl.replace(/\?tab1=timeline&id=([^\/]+)$/i,"' . $config['site_url'] . '/@$1"),historyurl=historyurl.replace(/\?tab1=messages&recipient_id=([A-Za-z0-9_]+)$/i,"' . $config['site_url'] . '/messages/$1"),historyurl=historyurl.replace(/\?tab1=story&id=([0-9]+)$/i,"' . $config['site_url'] . '/story/$1"),historyurl=historyurl.replace(/\?tab1=welcome&tab2=forgot_password$/i,"' . $config['site_url'] . '/forgot-password"),historyurl=historyurl.replace(/\?tab1=welcome&tab2=password_reset&id=([A-Za-z0-9_]+)$/i,"' . $config['site_url'] . '/password-reset/$1"),historyurl=historyurl.replace(/\?tab1=([^\/]+)&query=([^\/]+)$/i,"' . $config['site_url'] . '/$1/$2"),historyurl=historyurl.replace(/\?tab1=([^\/]+)&tab2=([^\/]+)&tab3=([^\/]+)$/i,"' . $config['site_url'] . '/$1/$2/$3"),historyurl=historyurl.replace(/\?tab1=([^\/]+)&tab2=([^\/]+)$/i,"' . $config['site_url'] . '/$1/$2"),historyurl=historyurl.replace(/\?tab1=([^\/]+)$/i,"' . $config['site_url'] . '/$1")),history.replaceState({},"miuan",historyurl))}),$(".dropdown-search-container").hide(),$(".dropdown-notification-container").hide(),$(".notification-nav").removeClass("header-nav-active"),$(".dropdown-more-container").hide(),$(".sc-lightbox-container").remove()}function startPageLoadingBar(){$(".page-loading-bar").show().width(50+30*Math.random()+"%")}function stopPageLoadingBar(){$(".page-loading-bar").width("101%").delay(200).fadeOut(400,function(){$(this).width("0")})}$(document).on("click","*[data-href]",function(r){r.preventDefault(),startPageLoadingBar(),SK_loadPage($(this).attr("data-href")),$(document).scrollTop(0)});</script>' : "";
$themeData['header_tags'] = \miuan\UI::view('global/header/all');

/* Plugin Theme Data */
$themeData['header_tags'] .= ($PLUGINS['MediaElementJs'] == true) ? '<script src="' . $site_url . '/extra/MediaElementJs/mediaelement-and-player.min.js"></script>
    <link href="' . $site_url . '/extra/MediaElementJs/min.css" rel="stylesheet">' : "";
$themeData['header_tags'] .= \miuan\Addons::invoke(array('head_tags_add_content', 'string'));
