<div class="list-column fan-id-{{LIST_LIKE_USER_ID}}">
    <table border="0" width="100%" cellspacing="0" cellpadding="0">
    <tr>
        <td width="38px" align="left" valign="middle">
            <a href="{{LIST_LIKE_USER_URL}}" data-href="?tab1=timeline&id={{LIST_LIKE_USER_USERNAME}}">
                <img width="32px" height="32px" class="radius100" src="{{LIST_LIKE_USER_THUMBNAIL_URL}}" alt="{{LIST_LIKE_USER_NAME}}">
            </a>
        </td>
        <td align="left" valign="middle">
            <a class="bold-500" href="{{LIST_LIKE_USER_URL}}" data-href="?tab1=timeline&id={{LIST_LIKE_USER_USERNAME}}">
                {{LIST_LIKE_USER_NAME}}
            </a>
        </td>
    </tr>
    </table>
</div>