<a class="list-column column-hover" href="{{LIST_RECIPIENT_CONVO_URL}}" data-href="?tab1=timeline&tab2=settings&tab3=messages&recipient_id={{LIST_RECIPIENT_USERNAME}}&id={{TIMELINE_USERNAME}}">
    <table border="0" width="100%" cellspacing="0" cellpadding="0">
        <tr>
        <td width="38px" align="left" valign="middle">
            <img width="32px" height="32px" class="radius100" src="{{LIST_RECIPIENT_THUMBNAIL_URL}}" alt="{{LIST_RECIPIENT_NAME}}">
        </td>
        <td align="left" valign="middle">
            <div class="bold-500">
                {{LIST_RECIPIENT_NAME}}
                
                <span class="update-alert">
                    {{LIST_RECIPIENT_MESSAGES_COUNT}}
                </span>
            </div>
        </td>
        </tr>
    </table>
</a>