<div class="float-left span25">

    
    <div class="list-wrapper">
        <div class="list-header">
            @menu_label@
        </div>
        
        <a class="list-column column-hover" href="{{GENERAL_SETTINGS_URL}}" data-href="?tab1=timeline&tab2=settings&tab3=general_settings&id={{TIMELINE_USERNAME}}">
            @general_settings_label@
        </a>
        
        <a class="list-column column-hover" href="{{PRIVACY_SETTINGS_URL}}" data-href="?tab1=timeline&tab2=settings&tab3=privacy&id={{TIMELINE_USERNAME}}">
            @privacy_settings_label@
        </a>
        
        {{ADMIN_SETTINGS_LINK}}
        

        

    </div>
</div>