<form class="welcome-form forgotpass-form" method="post">
    <div class="form-header">
        <div class="float-left">
            @forgot_password@?
        </div>

        <div class="float-right">
            <a href="{{LOGIN_TAB_URL}}">
                @log_in@
            </a>
        </div>

        <div class="float-clear"></div>
    </div>

    <div class="form-content">
        <div class="input-wrapper">
            <input type="text" name="forgotpass_id" value="@login_id_label@" placeholder="@login_id_label@" data-placeholder="@login_id_label@" autocomplete="off">
        </div>
        
        <button class="submit-btn active">
            <i class="icon-inbox progress-icon"></i> @reset_password_reset@
        </button>
    </div>
</form>