<form class="welcome-form passwordreset-form" method="post">
    <div class="form-header">
        @reset_password_label@
    </div>
    <div class="form-content">
        <div class="input-wrapper">
            <input type="text" name="pr_password" placeholder="@new_password_label@" autocomplete="off">
        </div>
        <button class="submit-btn active">
            <i class="icon-signin progress-icon"></i> @reset@
        </button>
    </div>
    <input type="hidden" name="pr_token" value="{{GET_ID}}">
</form>