<div class="input-wrapper">
    <table border="0" width="100%" cellspacing="0" cellpadding="0">
    <tr>
        <td width="85px" align="left" valign="middle">
            <img class="captcha" src="{{CAPTCHA_IMAGE_SRC}}">
        </td>
        <td align="left" valign="middle">
            <input type="text" value="@captcha_label@" placeholder="@captcha_label@" data-placeholder="@captcha_label@" autocomplete="off" data-copy-to=".register-captcha-input">
            <input class="register-captcha-input" type="hidden" name="captcha">
        </td>
    </tr>
    </table>
</div>